# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leakwatch < Formula
  desc "High-performance secret scanner for codebases, Git histories, and container images"
  homepage "https://github.com/cemililik/Leakwatch"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.4.0/leakwatch_1.4.0_darwin_amd64.tar.gz"
      sha256 "5506393d782fcb2887a9e6af8e2f79d4b5b5e8490889902355373785233ce990"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.4.0/leakwatch_1.4.0_darwin_arm64.tar.gz"
      sha256 "0334048d2db69eef7d9d61c33ab77ac18eec802f7f3e726819e8c37a886b6658"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.4.0/leakwatch_1.4.0_linux_amd64.tar.gz"
      sha256 "c53a62e302571f5f37ac3005deffc0c64fa9f92bc9184b2770359c7f1e64b7df"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.4.0/leakwatch_1.4.0_linux_arm64.tar.gz"
      sha256 "d47d487e9b173906730ae40bea1dafd6b5d81d593f2822c116295a2d9c2084a5"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  test do
    system "#{bin}/leakwatch", "version"
  end
end
