# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leakwatch < Formula
  desc "High-performance secret scanner for codebases, Git histories, and container images"
  homepage "https://github.com/cemililik/Leakwatch"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.3.0/Leakwatch_1.3.0_darwin_amd64.tar.gz"
      sha256 "46836546ffe7f9a928f545a6693b87795b526460a6c765ce27ad43fd8f7581e4"

      define_method(:install) do
        bin.install "Leakwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.3.0/Leakwatch_1.3.0_darwin_arm64.tar.gz"
      sha256 "893e84161395e615798fde4bf14b31e0136a2c7f501ab3628e1b298bce28cf74"

      define_method(:install) do
        bin.install "Leakwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.3.0/Leakwatch_1.3.0_linux_amd64.tar.gz"
      sha256 "3a66bfae6c42a5843fe27ae8b2e6dbbaafc0be313532a0449ab96713991b402f"
      define_method(:install) do
        bin.install "Leakwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.3.0/Leakwatch_1.3.0_linux_arm64.tar.gz"
      sha256 "54c99c70b244514c3b3ddc236c374db727d10b8ab929d0e43cdb6b5cb4eed4d5"
      define_method(:install) do
        bin.install "Leakwatch"
      end
    end
  end

  test do
    system "#{bin}/leakwatch", "version"
  end
end
