# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leakwatch < Formula
  desc "High-performance secret scanner for codebases, Git histories, and container images"
  homepage "https://github.com/cemililik/Leakwatch"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.3.1/leakwatch_1.3.1_darwin_amd64.tar.gz"
      sha256 "f854d9c55f49fb73237ba791f4e636eb4b7ba4796c0dbeeea72a463592810e3a"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.3.1/leakwatch_1.3.1_darwin_arm64.tar.gz"
      sha256 "bb67edbe1a710710cf20a389e409088668218e0b6de314d07a4c05a036358530"

      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.3.1/leakwatch_1.3.1_linux_amd64.tar.gz"
      sha256 "4ed0c45d40a2c0a7196af1f6eb1af7e051c6a21b2ac33d798e9927027d1c02ab"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cemililik/Leakwatch/releases/download/v1.3.1/leakwatch_1.3.1_linux_arm64.tar.gz"
      sha256 "9c0f7333b1ea831f774748db286ecc7b0e9182c81c66d8eeb18f6aa613ed685c"
      define_method(:install) do
        bin.install "leakwatch"
      end
    end
  end

  test do
    system "#{bin}/leakwatch", "version"
  end
end
